In [1]:
import torch

In [3]:
x = torch.tensor([[1, 2, 3, 4,], [12, 33, 4, 5]])

In [5]:
y = torch.tensor([[22, 11, 22, 344, 66], [22, 11, 22, 11, 88]])

In [6]:
z = torch.tensor([[11, 7, 3, 22 , 90], [16, 192, 342, 789, 105]])

In [7]:
my= torch.cat([x, y], 1)

In [8]:
print(my)

tensor([[  1,   2,   3,   4,  22,  11,  22, 344,  66],
        [ 12,  33,   4,   5,  22,  11,  22,  11,  88]])


In [9]:
my_ = torch.cat([my, z], 1)

In [10]:
my_

tensor([[  1,   2,   3,   4,  22,  11,  22, 344,  66,  11,   7,   3,  22,  90],
        [ 12,  33,   4,   5,  22,  11,  22,  11,  88,  16, 192, 342, 789, 105]])

In [11]:
my1 = torch.cat([x, y, z], 1)

In [12]:
my1

tensor([[  1,   2,   3,   4,  22,  11,  22, 344,  66,  11,   7,   3,  22,  90],
        [ 12,  33,   4,   5,  22,  11,  22,  11,  88,  16, 192, 342, 789, 105]])

In [13]:
g = y.clone()

In [14]:
g

tensor([[ 22,  11,  22, 344,  66],
        [ 22,  11,  22,  11,  88]])

In [15]:
y 

tensor([[ 22,  11,  22, 344,  66],
        [ 22,  11,  22,  11,  88]])

In [16]:
2 + y

tensor([[ 24,  13,  24, 346,  68],
        [ 24,  13,  24,  13,  90]])

In [17]:
g

tensor([[ 22,  11,  22, 344,  66],
        [ 22,  11,  22,  11,  88]])

In [18]:
import torch.nn.functional as F

In [23]:
x.shape[:]

torch.Size([2, 4])

In [24]:
k = F.interpolate(g, x.shape[:], mode = 'bilinear')

NotImplementedError: Input Error: Only 3D, 4D and 5D input Tensors supported (got 2D) for the modes: nearest | linear | bilinear | bicubic | trilinear (got bilinear)